### ISSUE TITLE
hcaptcha broken not letting me log into discord

### ISSUE THREAD

**Issue by clumsykiller** [binary-person/womginx#46] opened 2021-11-09 14:42 UTC

**Comment by clumsykiller** [comment] 2021-11-09 14:47
@binary-person

**Comment by clumsykiller** [comment] 2021-11-09 14:47
and how fast would you be able to fix it?

**Comment by zdc54** [comment] 2021-11-09 14:54
same

**Comment by clumsykiller** [comment] 2021-11-09 15:02
i just hope he can fix it fast

**Comment by zdc54** [comment] 2021-11-09 15:03
coding takes time, and also binary-person uses they/them.

**Comment by clumsykiller** [comment] 2021-11-09 15:05
oh im sorry i didnt know and ok

**Comment by clumsykiller** [comment] 2021-11-09 15:07
i figured they were he/him because their profile description uses the word dude

**Comment by zdc54** [comment] 2021-11-09 15:59
it says binary in his name bruh

**Comment by zdc54** [comment] 2021-11-09 16:00
*realization*

**Comment by MayMay39** [comment] 2021-11-09 21:41
Yeah, I have the same problem, hCaptcha broke about 9PM EST last night and I think binary-person might've been bugfixing and accidentally broke it - or hCaptcha itself broke, I tried logging on on Discord with Corrosion

**Comment by binary-person** [comment] 2021-11-09 22:46
> coding takes time, and also binary-person uses they/them.

thanks for the consideration, but it's "he/him." binary just refers to 0101 binary.

anyway, this is a duplicate of #44

**Closed by binary-person** 2021-11-09 22:46 UTC
