### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by nobutprobably** [binary-person/womginx#73] opened 2022-01-10 13:50 UTC
says im violaiting some source code in heroku and this isnt the first time it has happened it happened onced then i forked it and it worked and now its not working anymore

**Comment by binary-person** [comment] 2022-01-11 01:04
duplicate of #71

**Closed by binary-person** 2022-01-11 01:04 UTC

**Comment by nobutprobably1320** [comment] 2022-01-12 00:19
ive already forked it and the same message still pops up ive even tried making a new account

**Comment by binary-person** [comment] 2022-01-12 01:14
if it doesn't work, i can't help you
