### ISSUE TITLE
website blocked

### ISSUE THREAD

**Issue by Barnac1ed** [binary-person/womginx#106] opened 2022-03-02 17:57 UTC
my school blocks the website when i go to discord, is there a way to make the URL of the website you are trying to go to encoded in base 64?

ex: (current) https://womginx.binary-person.repl.co/main/https://www.google.com/ => (my idea) https://womginx.binary-person.repl.co/main/aHR0cHM6Ly9nb29nbGUuY29t
(and ik those aren't the right URLs btw)

thx in advance!

**Comment by es183923** [comment] 2022-03-02 18:17
Duplicate of #43 

---
tldr, not possible

**Closed** 2022-03-02 22:57 UTC
