### ISSUE TITLE
safari

### ISSUE THREAD

**Issue by Atlas-Can-Code** [binary-person/womginx#47] opened 2021-11-11 13:41 UTC
Why does the demo link only work sometimes and then other times I get a 403 forbidden

**Comment by zdc54** [comment] 2021-11-11 15:02
it is what it is

**Comment by binary-person** [comment] 2021-11-12 00:58
im going to fix it later. regardless, this is a duplicate of #9, so I'll be closing this issue

**Closed by binary-person** 2021-11-12 00:58 UTC

**Comment by tomhatesnerds** [comment] 2021-12-24 10:45
403 error still happeninggg

**Comment by zdc54** [comment] 2021-12-26 19:08
Aren't you on Christmas break or something? You prob don't need a proxy right now lol. Go ahead and type a forward slash (like this "/" but without the quotation marks), it should look like, "https://sitename.herokuapp.com/".
