### ISSUE TITLE
zombs io and wiziz io not working

### ISSUE THREAD

**Issue by easella** [binary-person/womginx#12] opened 2021-03-18 15:09 UTC
![image](https://user-images.githubusercontent.com/74786054/111649113-73c76600-87da-11eb-8a26-bab6e727e6e2.png)
![image](https://user-images.githubusercontent.com/74786054/111777869-40441480-888a-11eb-9e79-58710f517fcf.png)

**Comment by binary-person** [comment] 2021-03-18 22:00
works for me. can you open chrome dev tools, go to console tab, and take a screenshot?

**Comment by easella** [comment] 2021-03-19 03:26
I am playing from a school computer, and I cannot access chrome dev tools.

**Comment by binary-person** [comment] 2021-03-19 11:48
if you can't provide me a screenshot, I cannot help you

**Comment by easella** [comment] 2021-03-19 12:02
I will do it later today

**Comment by easella** [comment] 2021-03-19 12:37
can you provide me a screen shot of what the game looks like for you?

**Comment by easella** [comment] 2021-03-19 12:40
can you provide me the url for the working version?

**Comment by binary-person** [comment] 2021-03-19 13:06
i see now. you need to update to the latest version, meaning you need to redeploy. the last version i broke something, which is later fixed in this version

**Comment by binary-person** [comment] 2021-03-19 13:06
tell me if it still breaks after you updated it

**Comment by easella** [comment] 2021-03-19 14:42
it is still not working and I redeployed it.
![image](https://user-images.githubusercontent.com/74786054/111797736-ccad0200-889f-11eb-8f44-dc2a0c15d3a2.png)

**Comment by binary-person** [comment] 2021-03-19 15:21
zombs works for me and i cannot reproduce this issue. reopen if you have a chrome dev tools screenshot under the console tab

**Closed by binary-person** 2021-03-19 15:21 UTC

**Comment by easella** [comment] 2021-03-19 16:00
I will do it later
